### PR TITLE
Airbrake optional, SMTP, default locales * readme 

### PR DESCRIPTION
**Pull request by tomdemeyer**

### CODE REVIEW

**Comment by rbjarnason** [comment]
@tomdemeyer This one looks fine - did you mean to delete the branch?  You can undelete it here I think.

**Comment by tomdemeyer** [comment]
I merged it into master; only made it for the pull request..
Do I understand correctly I deleted it too soon?

best,

--

Tom Demeyer
Waag Society
http://waag.org

**Comment by rbjarnason** [comment]
Yes, just undelete it then I can merge it into my master :)

**Comment by rbjarnason** [comment]
The waagsociety:work branch

**Comment by tomdemeyer** [comment]
Ok; is there again; learning git.. nice :)


--

Tom Demeyer
Waag Society
http://waag.org

**Comment by tomdemeyer** [comment]
cool. I assumed the pull request encapsulated all diffs..

**Comment by rbjarnason** [comment]
Thanks for your contributions @tomdemeyer - Have a great weekend :)

**Comment by tomdemeyer** [comment]
'weekend!

**Pull request merged**
